export const rakshaWords = ["Angel",
  "Beauty",
  "Princess",
  " My Lady",
  "Bebe",
  "Sunshine",
  "Cutie - pie",
  "Sweet Stuff",
  "Shortie",
  "Super Star",
  "Boss Lady",
  "Dolly",
  "Hot Stuff",
  "Wifey",
  "Dancing Queen",
  "Better Half",
  "Honey Butter",
  "Sweet Pea",
  "Cherry Pie",
  "Shortcake",
  "Cinderella",
  "Wonder Woman",
  "Khaleesi",
  "Empress",
  "Sleeping Beauty",
  "Honey Bunny",
  "Captain Marvel",
  "Honeybee",
  "Wildcat",
  "Butterfly",
  "Bluebird",
  "Ladybug",
  "Lil’ Mouse",
  "Ladybird",
  "Mi Corazón",
  "Cara Mia",
  "Liebling",
  "Mon chéri",
  "Xiao Bao",
  "Neshama Sheli",
  "Buah Hatiku",
  "Canim",
  "Principessa",
  "Habibi",
  "Amore mio"]


export const dilipWords = [
  "Prince charming",
  "Honey",
  "Babe",
  "Lovebug",
  "Cutie pie",
  "Cutie",
  "Darling",
  "Sweetie",
  "Sweetheart",
  "Beau",
  "Baby",
  "Dear",
  "Love",
  "My beloved",
  "Paramour",
  "Treasure",
  "Adored one",
  "My one and only",
  "Love dove",
  "My moon",
  "Dreamboat",
  "Lover",
  "My whole heart",
  "Love of my life",
  "Dearest",
  "Sugar",
  "My everything",
  "My soulmate",
  "My forever",
  "Angel",
  "Angel face",
  "Bumblebee",
  "Precious",
  "Sweetie pie",
  "Honey bunny ",
  "Boo",
  "Eternal flame",
  "My king",
  "My true love",
  "Handsome",
  "My heart",
  "Sunshine",
  "Sweetums",
  "My best friend",
  "King of my heart",
  "My knight",
  "My better half",
  "My forevermore",
  "Rockstar",
  "Superhero",
]